### ISSUE TITLE
Provide Better Attribute Syntax

### ISSUE THREAD

**Issue by khalidabuhakmeh** [billbogaiv/hybrid-model-binding#1]
## Currently

``` csharp
using Microsoft.AspNetCore.Mvc;

public class Person
{
    [FromQuery]
    public int Age { get; set; }

    [FromRoute]
    public string Name { get; set; }
}
```
## Proposed

``` csharp
using Microsoft.AspNetCore.Mvc;

public class Person
{
    [From("query", "route", "headers")]
    public int Age { get; set; }

    [From("body", "query")]
    public string Name { get; set; }
}
```

This approach reduces the stacks of attributes that may build up on a model. Additionally, if people have their convention for models. They could just create their own attribute to avoid _magic strings_.

``` csharp
public class BodyQueryAttribute : FromAttribute {
  public BodyQueryAttribute()
     : base("body", "query") { }
}
```

**Comment by khalidabuhakmeh** [comment]
oh I also noticed a nice side effect of the **"new"** syntax would be that you can now place significance on the order that value provider keys are passed in.

### Update

Also, this approach would allow you to get rid of the `isGreedy` parameter function because you could just replace it with a `GreedyAttribute`.

``` csharp
public class GreedyAttribute : FromAttribute {
   public GreedyAttribute() 
     :base ("query", "routes", "body", "headers") {
          this.ModelProviders = /* Get All Other registered providers */;
     }
}
```

then do this.

``` csharp
using Microsoft.AspNetCore.Mvc;

public class Person
{
    [Greedy]
    public int Age { get; set; }

    [Greedy]
    public string Name { get; set; }
}
```

P.S. I am not sure I like the word **Greedy**, sounds negative.

**Comment by billbogaiv** [comment]
Thanks for the feedback, @khalidabuhakmeh. I am looking to incorporate better property-attribute syntax similar to your provided example. I was initially hesitant to use "magic strings", but cannot think of a better way which allows compile-time safety and expandability. The library itself will provide something like:

``` csharp
public sealed class ValueProvider
{
    public const string Form = "form";
    public const string Route = "route";
    public const string Query = "query";
}
```

``` csharp
using Microsoft.AspNetCore.Mvc;

public class Person
{
    [From(ValueProvider.Query, ValueProvider.Route)]
    public int Age { get; set; }
}
```

But, the user is free to use strings directly.

**Comment by billboga** [comment]
As far as **greedy** is concerned, I am open to another word... However, the word should reference the property's ability to cascade bind across multiple providers. There is a big change coming soon in the default implementation which prevents a property from getting bound to both model binder and then value provider (unless allowed by setting this *greedy* field to `true`). This boolean field will also prevent a value from getting bound to multiple value providers. Some of my front-runners:

`canCascade`
`isEager`
`isUnsafe`

**Comment by billboga** [comment]
The previous example would look like this:

```csharp
using Microsoft.AspNetCore.Mvc;

public class Person
{
    [From(CanCascade = true, FromProvider.Query, FromProvider.Route)]
    public int Age { get; set; }
}
```

**Comment by billbogaiv** [comment]
Library has been revamped to follow non-overlapping binding between model binders and value providers. Once a property has been bound, it will not get overwritten (unless `isUnsafe = true`). Additionally, if a property should only be bound to a specific binder/provider, then it will not get set even if an available provider _could_.

https://www.nuget.org/packages/HybridModelBinding/0.3.0
