### ISSUE TITLE
Could there be a release with HybridMvcBuilderExtensions?

### ISSUE THREAD

**Issue by Meberem** [billbogaiv/hybrid-model-binding#17]
I spent a little while trying to figure out why I couldn't use the awesome looking `.AddHybridModelBinder()` only to find out it hasn't actually been released yet. Would it be possible to create a release with that functionality in please?

**Comment by billbogaiv** [comment]
![Guy smacking his forehead](https://media.giphy.com/media/cn0Wfcg1pjtUA/giphy.gif)

Yes. I really need to setup CD. Look for the release within the next twelve-hours.

**Comment by billbogaiv** [comment]
All done: https://www.nuget.org/packages/HybridModelBinding/0.10.0
