### ISSUE TITLE
Add a sample project

### ISSUE THREAD

**Issue by khalidabuhakmeh** [billbogaiv/hybrid-model-binding#2]
The sample project should show how to use all the value providers, and let users exercise the binders.

**Comment by billbogaiv** [comment]
I have a sample in a local branch and will push once the big changes settle down. I anticipate this happening within the next couple weeks.

**Comment by jotatoledo** [comment]
Any updates? seems like the examples in the readme file are really out of date.

**Comment by khalidabuhakmeh** [comment]
Hi @jotatoledo we haven't had a chance to circle back to this project. We will in the next couple of months.

**Comment by billbogaiv** [comment]
@jotatoledo: should be all set with ASP.NET Core 2.0.

Note: ASP.NET Core 2.1.x is not possible at the moment due to: https://github.com/billbogaiv/hybrid-model-binding/issues/11. 

https://www.nuget.org/packages/HybridModelBinding/0.6.0
