### ISSUE TITLE
Collections are not being bound

### ISSUE THREAD

**Issue by derekgreer** [billbogaiv/hybrid-model-binding#21]
Issue Version:  0.4.0

I'm attempting to bind to a collection as outlined here: [https://haacked.com/archive/2008/10/23/model-binding-to-a-list.aspx/](url).

I have a model object defined as follows:

```
    public class GetRemittancesRequest
    {
        public int AccountId { get; set; }
        public DateTime? TransactionDate { get; set; }
        public decimal? TransactionAmount { get; set; }
        public ICollection<string> Expands { get; set; } 
    }
```

If I define my controller action as ```public IActionResult GetRemittances(GetRemittancesRequest request)``` then the Expands does not get bound, but if I define as follows then both the Expands property as well as the expands parameter are populated:

```public IActionResult GetRemittances(GetRemittancesRequest request, ICollection<string> expands)```

I don't quite understand why the second parameter is triggering the Expands property to get populated, but I'd of course like to not have the explicit expands to do so.

I'm still on version 0.4.0 because my project is targeting an 4.5.2 and upgrading to 4.6.2 is causing me some backward compatibility issues with other dependencies at the moment.

**Comment by billbogaiv** [comment]
https://www.nuget.org/packages/HybridModelBinding/0.12.0 has support for `net451` (ref. https://github.com/billbogaiv/hybrid-model-binding/commit/b17c978522b9f909ad86e74971e87de6c3909fd4).

I also started a PR (https://github.com/billbogaiv/hybrid-model-binding/pull/22) for dealing with collections. I'm going to let it sit for a few days and think if there's any other way to handle it. I'll probably need to add more checks, too.

**Comment by billbogaiv** [comment]
https://www.nuget.org/packages/HybridModelBinding/0.14.0 implements collections as well as some other new features. Collection-support will probably only work for simple-types at the moment. I have not done exhaustive testing.

**Comment by billbogaiv** [comment]
Doing some belated house cleaning. Issue has been resolved.

![Rick and Morty house-cleaning](https://media.giphy.com/media/Qvpxb0bju1rEp9Nipy/giphy.gif)
