### ISSUE TITLE
FromHeader binding

### ISSUE THREAD

**Issue by artyom-p** [billbogaiv/hybrid-model-binding#23]
Is it possible somehow to bind properties to header values?

**Comment by billbogaiv** [comment]
Not yet. [HeaderModelBinder](https://github.com/aspnet/Mvc/blob/8d66f104f7f2ca42ee8b21f75b0e2b3e1abe2e00/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/HeaderModelBinder.cs) exists in the aspnet/Mvc repo., but it's for very simple situations. I don't know why Microsoft never added a `HeaderValueProvider` to go with the other value providers. I postponed writing my own thinking they would eventually do it...

**Comment by billbogaiv** [comment]
🎉 https://www.nuget.org/packages/HybridModelBinding/0.13.0

```csharp
public class Person
{
    [From(Source.Header)]
    public int Age { get; set; }
}
```

```
curl -X GET \
  http://localhost/ \
  -H 'Age: 42'
```

**Comment by artyom-p** [comment]
Wow, thank you!

**Comment by artyom-p** [comment]
Hey, binding works perfectly, just a small proposal, it would be great to have a possibility to override a binding name.

For example i have a  header - x-request-id, and by default binder is unable to bind header to property RequestId (unfortunately it's no possible to use dashes in names). 

As a solution, aditional parameter for an attribute could work. This could be also helpful not only for header binding.

**Comment by billbogaiv** [comment]
https://www.nuget.org/packages/HybridModelBinding/0.14.0 implements a new `[HybridBindProperty]`-attribute that will allow you to reference a separate header-name. There are some additional features which can be found in the [README](https://github.com/billbogaiv/hybrid-model-binding/blob/0d75151b2c40bfab9136be5668e9fb34c3e2a16b/README.md).

**Comment by artyom-p** [comment]
That's a great news! Great update!

**Comment by billbogaiv** [comment]
Doing some belated house cleaning. Issue has been resolved.

![Rick house-cleaning](https://media.giphy.com/media/MYDEVtn9Zcq6BonFVl/giphy.gif)
