### ISSUE TITLE
Incompatible with a project that also uses WebApiCompatShim

### ISSUE THREAD

**Issue by Place1** [billbogaiv/hybrid-model-binding#28]
I've got a legacy project that originally used Web API and was ported to Dotnet core making use of microsoft's [WebApiCompatShim](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim/).

I've got an API method that looks like this `public List<MyModel> GetMyModel(int? size = null)`.

HybridModelBinding will throw an error [on this line](https://github.com/billbogaiv/hybrid-model-binding/blob/master/src/HybridModelBinding/HybridModelBinder.cs#L114-L115) because it can't find a model of type `Nullable<int>`. The last resort to set the value of `hydratedModel` using `Activator.CreateInstance` also returns null.

Is there a way I can tell hybrid model binder to ignore WebApi controllers? I actually only need the library for MVC controllers.

**Comment by billbogaiv** [comment]
https://www.nuget.org/packages/HybridModelBinding/0.15.0 will correct the problem. The default convention did not have enough constraints to not bind against non-class types.

**Comment by billbogaiv** [comment]
This issue should be resolved. 

![closed!](https://media.giphy.com/media/MZppavoFOeIlrcWMfK/giphy.gif)
