### ISSUE TITLE
when used with ApiController attribute in core 2.2 the binding errors are reflected in modelstate

### ISSUE THREAD

**Issue by greenbox64** [billbogaiv/hybrid-model-binding#31]
when used with ApiController attribute in core 2.2 the binding errors are reflected in modelstate
so that the "Automatic HTTP 400 responses" can be fired by the mvc core api project

**Comment by billbogaiv** [comment]
Not sure what this issue means, but sounds similar to https://github.com/billbogaiv/hybrid-model-binding/issues/41. I'm going to post any further updates there.
