### ISSUE TITLE
Rename Project To Smoothie?

### ISSUE THREAD

**Issue by khalidabuhakmeh** [billbogaiv/hybrid-model-binding#4]
Call this project Smoothie because of a few factors:
- It allows you to mix value providers and model binders into one delicious model.
- You feel `sooo smooth` when you use it.
## Horizontal

![smoothie_horizontal](https://cloud.githubusercontent.com/assets/228256/16710612/b6964452-4602-11e6-8bfc-60c4caa367b6.png)
## Centered

![smoothie_centered](https://cloud.githubusercontent.com/assets/228256/16710616/d29e8c54-4602-11e6-8e35-fbf439257a0e.png)
## Square / Icon

![smoothie_square](https://cloud.githubusercontent.com/assets/228256/16710614/b9c92496-4602-11e6-9ffc-dd20fdf93dbf.png)

**Comment by billbogaiv** [comment]
Will have to think about this. Do you have references for the imagery?

**Comment by billbogaiv** [comment]
https://thenounproject.com/search/?q=smoothie&i=81258

**Comment by khalidabuhakmeh** [comment]
I am a pro member of the noun project, so technically don't have to credit the creator but probably still should :)
