### ISSUE TITLE
FYI, a cleaner way to access Services in AddHybridModelBinder()

### ISSUE THREAD

**Issue by ericsampson** [billbogaiv/hybrid-model-binding#50]
I noticed that [here](https://github.com/billbogaiv/hybrid-model-binding/blob/6444de79e26e321bc2438883bfb049b32cdebd10/src/HybridModelBinding/HybridMvcBuilderExtensions.cs#L55) in `AddHybridModelBinder()` that it's building a serviceprovider.

There's a cleaner way to do this, that doesn't require building an intermediate serviceprovider (and the drawbacks it entails):
https://andrewlock.net/accessing-services-when-configuring-mvcoptions-in-asp-net-core/

I don't have time right this second to make a PR, but wanted to note it at least.

Cheers!

**Comment by billbogaiv** [comment]
Thanks for the feedback. That was fun to implement.
