### ISSUE TITLE
Add Source.Claim to allow binding from ClaimsPrincipal

### ISSUE THREAD

**Issue by Misiu** [billbogaiv/hybrid-model-binding#58]
I'm searching for a custom model binder to use in .net 5 REST API project.
Your HybridModelBinder is almost perfect, but it lacks the ability to bind specific claim to model property.
The use case is simple. You need to get id of the user that is doing the request.

I've used this code in the past:

```
namespace Utils.Binders
{
    [AttributeUsage(AttributeTargets.Parameter)]
    public class FromClaimAttribute : Attribute, IBindingSourceMetadata, IModelNameProvider
    {
        public BindingSource BindingSource => ClaimBindingSource.Claim;

        public FromClaimAttribute(string type)
        {
            Name = type;
        }

        public string Name { get; }
    }

    public class ClaimValueProviderFactory : IValueProviderFactory
    {
        public Task CreateValueProviderAsync(ValueProviderFactoryContext context)
        {
            context.ValueProviders.Add(new ClaimValueProvider(ClaimBindingSource.Claim, context.ActionContext.HttpContext.User));
            return Task.CompletedTask;
        }
    }

    public class ClaimValueProvider : BindingSourceValueProvider
    {
        private readonly ClaimsPrincipal _claimsPrincipal;

        public ClaimValueProvider(BindingSource bindingSource, ClaimsPrincipal claimsPrincipal) : base(bindingSource)
        {
            _claimsPrincipal = claimsPrincipal;
        }

        public override bool ContainsPrefix(string prefix) => _claimsPrincipal.HasClaim(claim => claim.Type == prefix);

        public override ValueProviderResult GetValue(string key)
        {
            var claimValue = _claimsPrincipal.FindFirstValue(key);
            return claimValue != null ? new ValueProviderResult(claimValue) : ValueProviderResult.None;
        }
    }

    public static class ClaimBindingSource
    {
        public static readonly BindingSource Claim = new(
            "Claim",
            "BindingSource_Claim",
            isGreedy: false,
            isFromRequest: true);
    }
}
```

maybe a similar value provider factory could be added to your project?

**Comment by Misiu** [comment]
@billbogaiv if you have time please take a look at my PR.
Any plans to maintain and improve this awesome project?

**Comment by billbogaiv** [comment]
Thanks for the PR. I think this is a great addition.

> Any plans to maintain and improve this awesome project?

Yes, although this project hasn't had much attention from me in several months. Somewhere on the horizon, I want to review the existing set of issues, add unit testing, and possibly look at expanding either the README or WIKI... and *maybe* start to submit RFPs to tech meetups like [TechBash](https://techbash.com/).

**Comment by billbogaiv** [comment]
Update published to NuGet: https://www.nuget.org/packages/HybridModelBinding/0.18.1-alpha.5

**Comment by Misiu** [comment]
@billbogaiv thank you for accepting my PR and creating a new NuGet package. I'll add it right away to my project.
I'll review the project and create some code-cleanup PR's (mostly variable names and some LINQ optimizations suggested by Resharper).
